name = "EnsembleInversion"
uuid = "e03f8fd3-a2ff-47f5-ac97-ba7f0577c430"
authors = ["Francesco Alemanno <francescoalemanno710@gmail.com>"]
version = "1.0.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "^1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]
